#!/usr/bin/env python3
"""Writes lib/core/media/policy/stamp_font_coverage.g.dart: the characters each
stamp font can draw, as sorted code point ranges.

ffmpeg's drawtext has no per-glyph fallback, so `StampFontPolicy` picks the
font from the text; it cannot read a font's cmap at runtime. Run from the
repository root after changing a stamp font (needs fontTools):

    python3 tool/fonts/make_stamp_coverage.py
"""

from fontTools.ttLib import TTFont

FONTS = [
    ("rubik", "assets/fonts/Rubik-Medium.ttf"),
    ("yuseiMagic", "assets/fonts/YuseiMagic-Regular.ttf"),
    ("notoSansSc", "assets/fonts/NotoSansSC-Medium.otf"),
]
OUTPUT = "lib/core/media/policy/stamp_font_coverage.g.dart"


def ranges(path):
    points = sorted(TTFont(path).getBestCmap())
    out = []
    for point in points:
        if out and point == out[-1][1] + 1:
            out[-1][1] = point
        else:
            out.append([point, point])
    return out


def main():
    lines = [
        "// GENERATED by tool/fonts/make_stamp_coverage.py. Do not edit.",
        "// dart format off",
        "",
        "/// The code points each stamp font draws: sorted, inclusive",
        "/// `start, end` pairs (`StampFontPolicy`).",
        "abstract final class StampFontCoverage {",
    ]
    for name, path in FONTS:
        flat = ", ".join(f"{a}, {b}" for a, b in ranges(path))
        lines.append(f"  /// `{path}`.")
        lines.append(f"  static const List<int> {name} = <int>[{flat}];")
        lines.append("")
    lines[-1] = "}"
    with open(OUTPUT, "w") as out:
        out.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
