// Writes the translated iOS permission prompts,
// ios/Runner/<language>.lproj/InfoPlist.strings, from the app's own
// translations (assets/translations/<language>.json). Run it from the
// repository root after a translation changes:
//
//   dart run tool/ios/info_plist_strings.dart
//
// Only sentences a translator wrote are used: a prompt whose key a language
// lacks is left out of that file, and iOS shows the English text of
// ios/Runner/Info.plist instead. A language that translates none of them gets
// no file. A new language also needs its InfoPlist.strings added to the
// Runner target in Xcode, and its code in Info.plist's CFBundleLocalizations
// (test/app/native/ios_localizations_test.dart checks both).
//
// Pure Dart, so it runs on the plain Dart VM.

import 'dart:convert';
import 'dart:io';

/// The translation key that each Info.plist usage description is written
/// from. The English prompts live in Info.plist.
///
/// iOS has no usage description for notifications.
const Map<String, String> usageDescriptionKeys = <String, String>{
  'NSCameraUsageDescription': 'cameraPermissionDesc',
  'NSMicrophoneUsageDescription': 'cameraMicPermissionDesc',
  'NSPhotoLibraryUsageDescription': 'galleryPermissionBody',
  'NSLocationWhenInUseUsageDescription': 'locationPermissionPrompt',
};

const String translationsPath = 'assets/translations';

/// The file the app falls back to; iOS uses Info.plist for it.
const String fallbackLanguage = 'en';

String infoPlistStringsPath(String language) =>
    'ios/Runner/$language.lproj/InfoPlist.strings';

/// The InfoPlist.strings for [language] from its [translations], or null
/// when they translate none of the prompts.
String? infoPlistStrings(String language, Map<String, Object?> translations) {
  final List<String> lines = <String>[
    for (final MapEntry<String, String>(key: String plistKey, value: String key)
        in usageDescriptionKeys.entries)
      if (translations[key] case final String text when text.trim().isNotEmpty)
        '${_quoted(plistKey)} = ${_quoted(text)};',
  ];
  if (lines.isEmpty) return null;
  return '/* Generated by tool/ios/info_plist_strings.dart from '
      '$translationsPath/$language.json. Do not edit. */\n'
      '${lines.join('\n')}\n';
}

/// The languages with a translation file other than [fallbackLanguage],
/// sorted.
List<String> translatedLanguages() {
  final List<String> languages = <String>[
    for (final FileSystemEntity entity in Directory(
      translationsPath,
    ).listSync())
      if (entity is File)
        if (entity.uri.pathSegments.last case final String name
            when name.endsWith('.json') && !name.startsWith('._'))
          name.substring(0, name.length - '.json'.length),
  ]..remove(fallbackLanguage);
  return languages..sort();
}

Map<String, Object?> readTranslations(String language) =>
    (jsonDecode(File('$translationsPath/$language.json').readAsStringSync())
            as Map<String, Object?>)
        .cast<String, Object?>();

String _quoted(String text) =>
    '"${text.replaceAll(r'\', r'\\').replaceAll('"', r'\"').replaceAll('\n', r'\n')}"';

void main() {
  for (final String language in translatedLanguages()) {
    final File file = File(infoPlistStringsPath(language));
    final String? contents = infoPlistStrings(
      language,
      readTranslations(language),
    );
    if (contents == null) {
      if (file.existsSync()) file.deleteSync();
      stdout.writeln('$language: no translated prompt, English only');
      continue;
    }
    file
      ..createSync(recursive: true)
      ..writeAsStringSync(contents);
    stdout.writeln('$language: ${file.path}');
  }
}
