"""Writes the reminders' Android small icon from the app logo's shapes.

    python3 tool/icons/notification_icon.py [preview.png]

Writes android/app/src/main/res/drawable/ic_notification.xml: a 24 dp vector,
white on transparent. Android draws a notification's small icon from its
alpha only, so the full-colour launcher icon shows as a white blob.

The shapes are traced by hand from assets/images/app_logo.png (512 x 512):
the "1", the tilted video camera, and the notebook with its rings, page edge
and label window. They are mapped into the 24 x 24 viewport with a 1 dp
margin. With a path argument, it also saves a large preview (needs Pillow).
"""
import math
import sys

OUT = 'android/app/src/main/res/drawable/ic_notification.xml'

# The logo's content box: x 95..430, y 85..510.
X0, Y0, X1, Y1 = 95, 85, 430, 510
SCALE = 22 / (Y1 - Y0)
OX = (24 - (X1 - X0) * SCALE) / 2
OY = 1.0


def to_viewport(p):
    return (OX + (p[0] - X0) * SCALE, OY + (p[1] - Y0) * SCALE)


def rounded_rect(x0, y0, x1, y1, r, steps=6):
    pts = []
    for cx, cy, a0, a1 in (
        (x1 - r, y0 + r, -90, 0),
        (x1 - r, y1 - r, 0, 90),
        (x0 + r, y1 - r, 90, 180),
        (x0 + r, y0 + r, 180, 270),
    ):
        for i in range(steps + 1):
            a = math.radians(a0 + (a1 - a0) * i / steps)
            pts.append((cx + r * math.cos(a), cy + r * math.sin(a)))
    return pts


def rounded_polygon(pts, r, steps=4):
    """Rounds every corner of a convex polygon by radius r."""
    out = []
    for i, p1 in enumerate(pts):
        p0, p2 = pts[i - 1], pts[(i + 1) % len(pts)]
        v1 = (p0[0] - p1[0], p0[1] - p1[1])
        v2 = (p2[0] - p1[0], p2[1] - p1[1])
        u1 = (v1[0] / math.hypot(*v1), v1[1] / math.hypot(*v1))
        u2 = (v2[0] / math.hypot(*v2), v2[1] / math.hypot(*v2))
        angle = math.acos(max(-1, min(1, u1[0] * u2[0] + u1[1] * u2[1])))
        d = r / math.tan(angle / 2)
        a = (p1[0] + u1[0] * d, p1[1] + u1[1] * d)
        b = (p1[0] + u2[0] * d, p1[1] + u2[1] * d)
        for k in range(steps + 1):
            t = k / steps
            out.append(tuple(
                (1 - t) ** 2 * a[j] + 2 * (1 - t) * t * p1[j] + t * t * b[j]
                for j in (0, 1)
            ))
    return out


def rotated(pts, cx, cy, degrees):
    t = math.radians(degrees)
    c, s = math.cos(t), math.sin(t)
    return [(cx + x * c - y * s, cy + x * s + y * c) for x, y in pts]


ONE = rounded_polygon([
    (116, 112), (192, 96), (212, 96), (212, 248), (150, 248), (150, 152),
    (116, 158),
], 10)
CAMERA_BODY = rotated(rounded_rect(-56, -56, 56, 56, 18), 300, 188, -35)
CAMERA_LENS = rotated(
    rounded_polygon([(66, 0), (116, -44), (116, 44)], 10), 300, 188, -35)
RINGS = [rounded_rect(94, 356 + 52 * i, 152, 380 + 52 * i, 12)
         for i in range(3)]

# Filled with the even-odd rule: the page edge and the window are holes, and
# the two lines inside the window are filled again.
NOTEBOOK = [
    rounded_rect(118, 270, 392, 510, 14),
    [(132, 322), (392, 322), (392, 336), (132, 336)],
    rounded_rect(176, 356, 366, 474, 12),
    rounded_rect(214, 394, 328, 410, 8),
    rounded_rect(214, 426, 328, 442, 8),
]
SOLIDS = [ONE, CAMERA_BODY, CAMERA_LENS] + RINGS

XML = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/icons/notification_icon.py. Do not edit.
     The reminders' status-bar icon (the plugin's small icon): the app logo
     as a white silhouette on transparent, 24 dp. Android draws small icons
     from their alpha only, so the full-colour launcher icon showed as a
     white blob (Z MB-17). -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path
        android:fillColor="#FFFFFFFF"
        android:pathData="%s" />
    <path
        android:fillColor="#FFFFFFFF"
        android:fillType="evenOdd"
        android:pathData="%s" />
</vector>
'''


def path_data(polygons):
    parts = []
    for polygon in polygons:
        pts = [to_viewport(p) for p in polygon]
        parts.append('M%.2f,%.2f' % pts[0]
                     + ''.join('L%.2f,%.2f' % p for p in pts[1:]) + 'Z')
    return ''.join(parts)


def save_preview(path, scale=16):
    from PIL import Image, ImageChops, ImageDraw

    size = (24 * scale, 24 * scale)

    def mask(polygon):
        layer = Image.new('1', size, 0)
        ImageDraw.Draw(layer).polygon(
            [(x * scale, y * scale) for x, y in map(to_viewport, polygon)],
            fill=1)
        return layer

    shape = Image.new('1', size, 0)
    for polygon in SOLIDS:
        shape = ImageChops.logical_or(shape, mask(polygon))
    notebook = Image.new('1', size, 0)
    for polygon in NOTEBOOK:
        notebook = ImageChops.logical_xor(notebook, mask(polygon))
    shape = ImageChops.logical_or(shape, notebook)
    image = Image.new('RGBA', size, (40, 40, 40, 255))
    image.paste((255, 255, 255, 255), mask=shape.convert('L'))
    image.save(path)


if __name__ == '__main__':
    with open(OUT, 'w') as f:
        f.write(XML % (path_data(SOLIDS), path_data(NOTEBOOK)))
    if len(sys.argv) > 1:
        save_preview(sys.argv[1])
